global:
  scrape_interval:     2s # How often to scrape targets
  evaluation_interval: 2s # How often to evaluate rules

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "auth-service"
    static_configs:
      - targets: [ "host.docker.internal:2112" ]

